export const AREA = {
    FLOOR_LAYER: {
        TABLE_GAME: "tableGame",
        CAREER_AREA: "careerArea",
        AGENCY_AREA: "agencyArea",
        TUTO_AREA: "tutoArea",
        VIDEO_AGENCY: "videoAgency",
        HELP_TO_NEXT_STEP: "helpToNextStep",
        BET_ON_BETTER:"betOnBetter",
        SUPPORT_RH: "supportrh",
        BET_ON_TALENT: "betOnTalent",
        HELP_CAREER_AREA_POP_UP:"helpCareerArea_popup",
        BOT_3_NOTIFICATION: "bot3Notification",
        START_AREA: "startArea",
        PACTE_AREA: "pacteArea",
        BET_ON_AGENCY: "betOnAgencyArea",
        BET_ON_FUTUR: "betOnFutureArea",
        BET_ON_FUTUR_LINK_1: "betOnFutureLink1",
        BET_ON_FUTUR_LINK_2: "betOnFutureLink2",
        BET_ON_FUTUR_LINK_3: "betOnFutureLink3",
        BET_ON_FUTUR_LINK_4: "betOnFutureLink4",
        BET_ON_EXPERTISE: "betOnExpertiseArea",
        BET_ON_EXPERTISE_VIDEO1: "videoCloud",
        BET_ON_EXPERTISE_CITATION1: "citationCloud",
        BET_ON_EXPERTISE_VIDEO2: "videoDevops",
        BET_ON_EXPERTISE_CITATION2: "citationDevops",
        BET_ON_EXPERTISE_VIDEO3: "videoCyber",
        BET_ON_EXPERTISE_CITATION3: "citationCyber",
        BET_ON_EXPERTISE_VIDEO4: "videoAgilite",
        BET_ON_EXPERTISE_CITATION4: "citationAgilite",
        BET_ON_EXPERTISE_VIDEO5: "videoData",
        BET_ON_EXPERTISE_CITATION5: "citationData",
        BET_ON_EXPERTISE_CITATION6: "citationSoftware",
        BET_ON_YOU: "betOnYouArea",
        BET_ON_YOU_LINK1: "betOnYouLink1",
        BET_ON_YOU_LINK2: "betOnYouLink2",
        BET_ON_YOU_LINK3: "betOnYouLink3",
        QUEST_BOT1: "questBotArea1",
        QUEST_BOT2: "questBotArea2",
        QUEST_BOT3: "questBotArea3"
    },
    DOORS_LAYER: {
        ALL_DOORS_CLOSED : "allDoorsClosed",
        DOOR_CAREER_AREA : "door2Open",
        DOOR_AGENCY_AREA : "door3Open",
        ALL_DOORS_OPENED : "collisions"
    },
    EASTER_EGG: {
        RICK_ROLL: "rickRoll"
    }
}